print("AA");

// Make Crate more expensive
recipes.remove(new CTItemStack("actuallyadditions:blockGiantChest").get());
recipes.addShaped(new CTItemStack("actuallyadditions:blockGiantChest").get(), [[new CTItemStack("minecraft:chest").get(), new CTItemStack("ic2:plate:11").get(), new CTItemStack("minecraft:chest").get()], [new CTItemStack("ore:gemDiamond").get(), new CTItemStack("actuallyadditions:blockMisc:4").get(), new CTItemStack("ore:gemDiamond").get()], [new CTItemStack("minecraft:chest").get(), new CTItemStack("ic2:plate:12").get(), new CTItemStack("minecraft:chest").get()]]);

// Iron Casing needs IC2 Casing
recipes.remove(new CTItemStack("actuallyadditions:blockMisc:9").get());
recipes.addShaped(new CTItemStack("actuallyadditions:blockMisc:9").get(), [[new CTItemStack("ore:ingotIron").get() , new CTItemStack("ore:gemQuartzBlack").get(), new CTItemStack("ore:ingotIron").get()], [new CTItemStack("ore:gemQuartzBlack").get(), new CTItemStack("ore:machineBlockAdvanced").get(), new CTItemStack("ore:gemQuartzBlack").get()], [new CTItemStack("ore:ingotIron").get() , new CTItemStack("ore:gemQuartzBlack").get(), new CTItemStack("ore:ingotIron").get()]]);

// Coal Generator needs Calculator
recipes.remove(new CTItemStack("actuallyadditions:blockCoalGenerator").get());
recipes.addShaped(new CTItemStack("actuallyadditions:blockCoalGenerator").get(), [[new CTItemStack("sonarcore:ReinforcedStoneBlock").get(), new CTItemStack("ore:fuelCoke").get(), new CTItemStack("sonarcore:ReinforcedStoneBlock").get()], [new CTItemStack("sonarcore:ReinforcedStoneBlock").get(), new CTItemStack("actuallyadditions:blockMisc:9").get(), new CTItemStack("sonarcore:ReinforcedStoneBlock").get()], [new CTItemStack("sonarcore:ReinforcedStoneBlock").get(), new CTItemStack("ore:fuelCoke").get(), new CTItemStack("sonarcore:ReinforcedStoneBlock").get()]]);

// Atomic Reconstructor needs Calculator
recipes.remove(new CTItemStack("actuallyadditions:blockAtomicReconstructor").get());
recipes.addShaped(new CTItemStack("actuallyadditions:blockAtomicReconstructor").get(), [[new CTItemStack("calculator:ReinforcedIronIngot").get(), new CTItemStack("calculator:EnrichedGold").get(), new CTItemStack("calculator:ReinforcedIronIngot").get()], [new CTItemStack("calculator:EnrichedGold").get(), new CTItemStack("actuallyadditions:blockMisc:9").get(), new CTItemStack("calculator:EnrichedGold").get()], [new CTItemStack("calculator:ReinforcedIronIngot").get(), new CTItemStack("calculator:EnrichedGold").get(), new CTItemStack("calculator:ReinforcedIronIngot").get()]]);

// ESD
recipes.remove(new CTItemStack("actuallyadditions:blockInputter").get());
recipes.addShaped(new CTItemStack("actuallyadditions:blockInputter").get(), [[new CTItemStack("ore:plankWood").get(), new CTItemStack("ore:plankWood").get(), new CTItemStack("ore:plankWood").get()], [new CTItemStack("actuallyadditions:blockMisc:4").get(), new CTItemStack("minecraft:hopper").get(), new CTItemStack("actuallyadditions:blockMisc:4").get()], [new CTItemStack("ore:plankWood").get(), new CTItemStack("ore:plankWood").get(), new CTItemStack("ore:plankWood").get()]]);

// Battery
recipes.remove(new CTItemStack("actuallyadditions:itemBattery").get());
recipes.addShaped(new CTItemStack("actuallyadditions:itemBattery").get(), [[null, new CTItemStack("calculator:EnergyModule").get(), null], [new CTItemStack("actuallyadditions:itemCrystal:5").get(), new CTItemStack("actuallyadditions:itemMisc:8").get(), new CTItemStack("actuallyadditions:itemCrystal:5").get()], [new CTItemStack("actuallyadditions:itemCrystal:5").get(), new CTItemStack("actuallyadditions:itemCrystal:5").get(), new CTItemStack("actuallyadditions:itemCrystal:5").get()]]);

// Empowerer Tooltip
new CTItemStack("actuallyadditions:blockEmpowerer).addTooltip(format.red("(* triggers Age 3)")).get();

// Remove Prismarine Recipe
// mods.actuallyadditions.AtomicReconstructor.remove(new CTItemStack("minecraft:quartz").get());

// Empowerer Recipes
mods.actuallyadditions.Empowerer.remove(new CTItemStack("actuallyadditions:blockCrystal").get(), new CTItemStack("actuallyadditions:blockCrystalEmpowered").get());
mods.actuallyadditions.Empowerer.addRecipe(new CTItemStack("actuallyadditions:blockCrystal").get(),new CTItemStack("actuallyadditions:blockCrystalEmpowered").get(),new CTItemStack("extrautils2:ingredients").get(),new CTItemStack("minecraft:dye:1").get(),new CTItemStack("tconstruct:ingots:1").get(),new CTItemStack("techreborn:gem:3").get(),1000000,1000,1,0,0);
new CTItemStack("actuallyadditions:blockCrystalEmpowered).addTooltip(format.red("(* requires 4M RF to make)")).get();
mods.actuallyadditions.Empowerer.remove(new CTItemStack("actuallyadditions:itemCrystal").get(), new CTItemStack("actuallyadditions:itemCrystalEmpowered").get());
mods.actuallyadditions.Empowerer.addRecipe(new CTItemStack("actuallyadditions:itemCrystal").get(),new CTItemStack("actuallyadditions:itemCrystalEmpowered").get(),new CTItemStack("extrautils2:ingredients").get(),new CTItemStack("minecraft:dye:1").get(),new CTItemStack("tconstruct:ingots:1").get(),new CTItemStack("techreborn:gem:3").get(),100000,100,1,0,0);
new CTItemStack("actuallyadditions:itemCrystalEmpowered).addTooltip(format.red("(* requires 400k RF to make)")).get();

mods.actuallyadditions.Empowerer.remove(new CTItemStack("actuallyadditions:blockCrystal:1").get(), new CTItemStack("actuallyadditions:blockCrystalEmpowered:1").get());
mods.actuallyadditions.Empowerer.addRecipe(new CTItemStack("actuallyadditions:blockCrystal:1").get(),new CTItemStack("actuallyadditions:blockCrystalEmpowered:1").get(),new CTItemStack("minecraft:fish").get(),new CTItemStack("minecraft:prismarine_shard").get(),new CTItemStack("tconstruct:ingots").get(),new CTItemStack("tconstruct:materials:10").get(),2000000,2000,0,0,1);
new CTItemStack("actuallyadditions:blockCrystalEmpowered:1).addTooltip(format.red("(* requires 8M RF to make)")).get();
mods.actuallyadditions.Empowerer.remove(new CTItemStack("actuallyadditions:itemCrystal:1").get(), new CTItemStack("actuallyadditions:itemCrystalEmpowered:1").get());
mods.actuallyadditions.Empowerer.addRecipe(new CTItemStack("actuallyadditions:itemCrystal:1").get(),new CTItemStack("actuallyadditions:itemCrystalEmpowered:1").get(),new CTItemStack("minecraft:fish").get(),new CTItemStack("minecraft:prismarine_shard").get(),new CTItemStack("tconstruct:ingots").get(),new CTItemStack("tconstruct:materials:10").get(),200000,200,0,0,1);
new CTItemStack("actuallyadditions:itemCrystalEmpowered:1).addTooltip(format.red("(* requires 800k RF to make)")).get();

mods.actuallyadditions.Empowerer.remove(new CTItemStack("actuallyadditions:blockCrystal:2").get(), new CTItemStack("actuallyadditions:blockCrystalEmpowered:2").get());
mods.actuallyadditions.Empowerer.addRecipe(new CTItemStack("actuallyadditions:blockCrystal:2").get(),new CTItemStack("actuallyadditions:blockCrystalEmpowered:2").get(),new CTItemStack("forestry:ash").get(),new CTItemStack("bigreactors:minerals:1").get(),new CTItemStack("forestry:fertilizerCompound").get(),new CTItemStack("ic2:dust:11").get(),5000000,5000,0,0.2,1);
new CTItemStack("actuallyadditions:blockCrystalEmpowered:2).addTooltip(format.red("(* requires 20M RF to make)")).get();
mods.actuallyadditions.Empowerer.remove(new CTItemStack("actuallyadditions:itemCrystal:2").get(), new CTItemStack("actuallyadditions:itemCrystalEmpowered:2").get());
mods.actuallyadditions.Empowerer.addRecipe(new CTItemStack("actuallyadditions:itemCrystal:2").get(),new CTItemStack("actuallyadditions:itemCrystalEmpowered:2").get(),new CTItemStack("forestry:ash").get(),new CTItemStack("bigreactors:minerals:1").get(),new CTItemStack("forestry:fertilizerCompound").get(),new CTItemStack("ic2:dust:11").get(),500000,500,0,0.2,1);
new CTItemStack("actuallyadditions:itemCrystalEmpowered:2).addTooltip(format.red("(* requires 2M RF to make)")).get();

mods.actuallyadditions.Empowerer.remove(new CTItemStack("actuallyadditions:blockCrystal:3").get(), new CTItemStack("actuallyadditions:blockCrystalEmpowered:3").get());
mods.actuallyadditions.Empowerer.addRecipe(new CTItemStack("actuallyadditions:blockCrystal:3").get(),new CTItemStack("actuallyadditions:blockCrystalEmpowered:3").get(),new CTItemStack("actuallyadditions:itemMisc:5").get(),new CTItemStack("immersiveengineering:material:6").get(),new CTItemStack("tconstruct:materials:17").get(),new CTItemStack("minecraft:dye").get(),3000000,3000,0,0,0);
new CTItemStack("actuallyadditions:blockCrystalEmpowered:3).addTooltip(format.red("(* requires 12M RF to make)")).get();
mods.actuallyadditions.Empowerer.remove(new CTItemStack("actuallyadditions:itemCrystal:3").get(), new CTItemStack("actuallyadditions:itemCrystalEmpowered:3").get());
mods.actuallyadditions.Empowerer.addRecipe(new CTItemStack("actuallyadditions:itemCrystal:3").get(),new CTItemStack("actuallyadditions:itemCrystalEmpowered:3").get(),new CTItemStack("actuallyadditions:itemMisc:5").get(),new CTItemStack("immersiveengineering:material:6").get(),new CTItemStack("tconstruct:materials:17").get(),new CTItemStack("minecraft:dye").get(),300000,300,0,0,0);
new CTItemStack("actuallyadditions:itemCrystalEmpowered:3).addTooltip(format.red("(* requires 1.2M RF to make)")).get();

mods.actuallyadditions.Empowerer.remove(new CTItemStack("actuallyadditions:blockCrystal:4").get(), new CTItemStack("actuallyadditions:blockCrystalEmpowered:4").get());
mods.actuallyadditions.Empowerer.addRecipe(new CTItemStack("actuallyadditions:blockCrystal:4").get(),new CTItemStack("actuallyadditions:blockCrystalEmpowered:4").get(),new CTItemStack("minecraft:cactus").get(),new CTItemStack("ic2:nuclear:2").get(),new CTItemStack("calculator:CookedBroccoli").get(),new CTItemStack("tconstruct:materials:9").get(),6000000,6000,0,1,0);
new CTItemStack("actuallyadditions:blockCrystalEmpowered:4).addTooltip(format.red("(* requires 24M RF to make)")).get();
mods.actuallyadditions.Empowerer.remove(new CTItemStack("actuallyadditions:itemCrystal:4").get(), new CTItemStack("actuallyadditions:itemCrystalEmpowered:4").get());
mods.actuallyadditions.Empowerer.addRecipe(new CTItemStack("actuallyadditions:itemCrystal:4").get(),new CTItemStack("actuallyadditions:itemCrystalEmpowered:4").get(),new CTItemStack("minecraft:cactus").get(),new CTItemStack("ic2:nuclear:2").get(),new CTItemStack("calculator:CookedBroccoli").get(),new CTItemStack("tconstruct:materials:9").get(),600000,600,0,1,0);
new CTItemStack("actuallyadditions:itemCrystalEmpowered:4).addTooltip(format.red("(* requires 2.4M RF to make)")).get();

mods.actuallyadditions.Empowerer.remove(new CTItemStack("actuallyadditions:blockCrystal:5").get(), new CTItemStack("actuallyadditions:blockCrystalEmpowered:5").get());
mods.actuallyadditions.Empowerer.addRecipe(new CTItemStack("actuallyadditions:blockCrystal:5").get(),new CTItemStack("actuallyadditions:blockCrystalEmpowered:5").get(),new CTItemStack("minecraft:snow").get(),new CTItemStack("ic2:dust:15").get(),new CTItemStack("minecraft:bone_block").get(),new CTItemStack("minecraft:ghast_tear").get(),4000000,4000,1,1,1);
new CTItemStack("actuallyadditions:blockCrystalEmpowered:5).addTooltip(format.red("(* requires 16M RF to make)")).get();
mods.actuallyadditions.Empowerer.remove(new CTItemStack("actuallyadditions:itemCrystal:5").get(), new CTItemStack("actuallyadditions:itemCrystalEmpowered:5").get());
mods.actuallyadditions.Empowerer.addRecipe(new CTItemStack("actuallyadditions:itemCrystal:5").get(),new CTItemStack("actuallyadditions:itemCrystalEmpowered:5").get(),new CTItemStack("minecraft:snow").get(),new CTItemStack("ic2:dust:15").get(),new CTItemStack("minecraft:bone_block").get(),new CTItemStack("minecraft:ghast_tear").get(),400000,400,1,1,1);
new CTItemStack("actuallyadditions:itemCrystalEmpowered:5).addTooltip(format.red("(* requires 1.6M RF to make)")).get();

// Farmer Recipe
recipes.remove(new CTItemStack("actuallyadditions:blockFarmer").get());
recipes.addShaped(new CTItemStack("actuallyadditions:blockFarmer").get(), [[new CTItemStack("actuallyadditions:blockCrystal:5").get(), new CTItemStack("actuallyadditions:itemMisc:24").get(), new CTItemStack("actuallyadditions:blockCrystal:5").get()], [new CTItemStack("actuallyadditions:blockMisc:9").get(), new CTItemStack("calculator:AdvancedGreenhouse").get(), new CTItemStack("actuallyadditions:blockMisc:9").get()], [new CTItemStack("actuallyadditions:blockCrystal:5").get(), new CTItemStack("actuallyadditions:itemMisc:24").get(), new CTItemStack("actuallyadditions:blockCrystal:5").get()]]);

// Oil Generator Recipe
recipes.remove(new CTItemStack("actuallyadditions:blockOilGenerator").get());
recipes.addShaped(new CTItemStack("actuallyadditions:blockOilGenerator").get(), [[new CTItemStack("sonarcore:ReinforcedStoneBlock").get(), new CTItemStack("actuallyadditions:blockMisc:9").get(), new CTItemStack("sonarcore:ReinforcedStoneBlock").get()], [new CTItemStack("sonarcore:ReinforcedStoneBlock").get(), new CTItemStack("actuallyadditions:itemMisc:24").get(), new CTItemStack("sonarcore:ReinforcedStoneBlock").get()], [new CTItemStack("sonarcore:ReinforcedStoneBlock").get(), new CTItemStack("actuallyadditions:blockMisc:9").get(), new CTItemStack("sonarcore:ReinforcedStoneBlock").get()]]);
recipes.addShapeless(new CTItemStack("actuallyadditions:blockOilGenerator").get(), [new CTItemStack("actuallyadditions:blockOilGenerator").get()] );

// Travellers Bag
recipes.remove(new CTItemStack("actuallyadditions:itemBag").get());
recipes.addShaped(new CTItemStack("actuallyadditions:itemBag").get(), [[new CTItemStack("minecraft:string").get(), new CTItemStack("minecraft:leather").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:string").get(), new CTItemStack("bagginses:whiteT3").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:leather").get(), new CTItemStack("actuallyadditions:blockCrystal:3").get(), new CTItemStack("minecraft:leather").get()]]);
recipes.addShaped(new CTItemStack("actuallyadditions:itemBag").get(), [[new CTItemStack("minecraft:string").get(), new CTItemStack("minecraft:leather").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:string").get(), new CTItemStack("bagginses:lightBlueT3").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:leather").get(), new CTItemStack("actuallyadditions:blockCrystal:3").get(), new CTItemStack("minecraft:leather").get()]]);
recipes.addShaped(new CTItemStack("actuallyadditions:itemBag").get(), [[new CTItemStack("minecraft:string").get(), new CTItemStack("minecraft:leather").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:string").get(), new CTItemStack("bagginses:greenT3").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:leather").get(), new CTItemStack("actuallyadditions:blockCrystal:3").get(), new CTItemStack("minecraft:leather").get()]]);
recipes.addShaped(new CTItemStack("actuallyadditions:itemBag").get(), [[new CTItemStack("minecraft:string").get(), new CTItemStack("minecraft:leather").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:string").get(), new CTItemStack("bagginses:limeT3").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:leather").get(), new CTItemStack("actuallyadditions:blockCrystal:3").get(), new CTItemStack("minecraft:leather").get()]]);
recipes.addShaped(new CTItemStack("actuallyadditions:itemBag").get(), [[new CTItemStack("minecraft:string").get(), new CTItemStack("minecraft:leather").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:string").get(), new CTItemStack("bagginses:blackT3").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:leather").get(), new CTItemStack("actuallyadditions:blockCrystal:3").get(), new CTItemStack("minecraft:leather").get()]]);
recipes.addShaped(new CTItemStack("actuallyadditions:itemBag").get(), [[new CTItemStack("minecraft:string").get(), new CTItemStack("minecraft:leather").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:string").get(), new CTItemStack("bagginses:purpleT3").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:leather").get(), new CTItemStack("actuallyadditions:blockCrystal:3").get(), new CTItemStack("minecraft:leather").get()]]);
recipes.addShaped(new CTItemStack("actuallyadditions:itemBag").get(), [[new CTItemStack("minecraft:string").get(), new CTItemStack("minecraft:leather").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:string").get(), new CTItemStack("bagginses:pinkT3").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:leather").get(), new CTItemStack("actuallyadditions:blockCrystal:3").get(), new CTItemStack("minecraft:leather").get()]]);
recipes.addShaped(new CTItemStack("actuallyadditions:itemBag").get(), [[new CTItemStack("minecraft:string").get(), new CTItemStack("minecraft:leather").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:string").get(), new CTItemStack("bagginses:redT3").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:leather").get(), new CTItemStack("actuallyadditions:blockCrystal:3").get(), new CTItemStack("minecraft:leather").get()]]);
recipes.addShaped(new CTItemStack("actuallyadditions:itemBag").get(), [[new CTItemStack("minecraft:string").get(), new CTItemStack("minecraft:leather").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:string").get(), new CTItemStack("bagginses:magentaT3").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:leather").get(), new CTItemStack("actuallyadditions:blockCrystal:3").get(), new CTItemStack("minecraft:leather").get()]]);
recipes.addShaped(new CTItemStack("actuallyadditions:itemBag").get(), [[new CTItemStack("minecraft:string").get(), new CTItemStack("minecraft:leather").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:string").get(), new CTItemStack("bagginses:blueT3").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:leather").get(), new CTItemStack("actuallyadditions:blockCrystal:3").get(), new CTItemStack("minecraft:leather").get()]]);
recipes.addShaped(new CTItemStack("actuallyadditions:itemBag").get(), [[new CTItemStack("minecraft:string").get(), new CTItemStack("minecraft:leather").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:string").get(), new CTItemStack("bagginses:silverT3").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:leather").get(), new CTItemStack("actuallyadditions:blockCrystal:3").get(), new CTItemStack("minecraft:leather").get()]]);
recipes.addShaped(new CTItemStack("actuallyadditions:itemBag").get(), [[new CTItemStack("minecraft:string").get(), new CTItemStack("minecraft:leather").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:string").get(), new CTItemStack("bagginses:grayT3").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:leather").get(), new CTItemStack("actuallyadditions:blockCrystal:3").get(), new CTItemStack("minecraft:leather").get()]]);
recipes.addShaped(new CTItemStack("actuallyadditions:itemBag").get(), [[new CTItemStack("minecraft:string").get(), new CTItemStack("minecraft:leather").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:string").get(), new CTItemStack("bagginses:brownT3").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:leather").get(), new CTItemStack("actuallyadditions:blockCrystal:3").get(), new CTItemStack("minecraft:leather").get()]]);
recipes.addShaped(new CTItemStack("actuallyadditions:itemBag").get(), [[new CTItemStack("minecraft:string").get(), new CTItemStack("minecraft:leather").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:string").get(), new CTItemStack("bagginses:orangeT3").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:leather").get(), new CTItemStack("actuallyadditions:blockCrystal:3").get(), new CTItemStack("minecraft:leather").get()]]);
recipes.addShaped(new CTItemStack("actuallyadditions:itemBag").get(), [[new CTItemStack("minecraft:string").get(), new CTItemStack("minecraft:leather").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:string").get(), new CTItemStack("bagginses:cyanT3").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:leather").get(), new CTItemStack("actuallyadditions:blockCrystal:3").get(), new CTItemStack("minecraft:leather").get()]]);
recipes.addShaped(new CTItemStack("actuallyadditions:itemBag").get(), [[new CTItemStack("minecraft:string").get(), new CTItemStack("minecraft:leather").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:string").get(), new CTItemStack("bagginses:yellowT3").get(), new CTItemStack("minecraft:string").get()], [new CTItemStack("minecraft:leather").get(), new CTItemStack("actuallyadditions:blockCrystal:3").get(), new CTItemStack("minecraft:leather").get()]]);
new CTItemStack("actuallyadditions:itemBag).addTooltip(format.red("(* before crafting empty the Bagginses bag)")).get();

// Advanced Coil
recipes.remove(new CTItemStack("actuallyadditions:itemMisc:8").get());
recipes.addShaped(new CTItemStack("actuallyadditions:itemMisc:8").get(), [[new CTItemStack("ic2:cable:2).withTag({type: 2 , insulation: 0 }), new CTItemStack("ic2:cable:2").get().withTag({type: 2 , insulation: 0 }), new CTItemStack("ic2:cable:2").get().withTag({type: 2 , insulation: 0 })], [new CTItemStack("ic2:cable:2").get().withTag({type: 2 , insulation: 0 }), new CTItemStack("actuallyadditions:itemMisc:7").get(), new CTItemStack("ic2:cable:2").get().withTag({type: 2 , insulation: 0 })], [new CTItemStack("ic2:cable:2").get().withTag({type: 2 , insulation: 0 }), new CTItemStack("ic2:cable:2").get().withTag({type: 2 , insulation: 0 }), new CTItemStack("ic2:cable:2").get().withTag({type: 2 , insulation: 0 })]]).get();

// Ring of Growth
recipes.remove(new CTItemStack("actuallyadditions:itemGrowthRing").get());
recipes.addShaped(new CTItemStack("actuallyadditions:itemGrowthRing").get(), [[new CTItemStack("forestry:fruits:3").get(), new CTItemStack("actuallyadditions:itemCrystalEmpowered:5").get(), new CTItemStack("forestry:fruits:6").get()], [new CTItemStack("actuallyadditions:itemCrystalEmpowered:5").get(), new CTItemStack("actuallyadditions:itemMisc:6").get(), new CTItemStack("actuallyadditions:itemCrystalEmpowered:5").get()], [new CTItemStack("forestry:fruits:5").get(), new CTItemStack("actuallyadditions:itemCrystalEmpowered:5").get(), new CTItemStack("forestry:fruits:4").get()]]);

// Make Lava Factory cheaper  cant use lava for power anyway
recipes.remove(new CTItemStack("actuallyadditions:blockLavaFactoryController").get());
recipes.addShaped(new CTItemStack("actuallyadditions:blockLavaFactoryController").get(), [[new CTItemStack("actuallyadditions:itemMisc:8").get(), new CTItemStack("actuallyadditions:blockMisc:9").get(), new CTItemStack("actuallyadditions:itemMisc:8").get()], [new CTItemStack("actuallyadditions:blockCrystal:5").get(), new CTItemStack("actuallyadditions:itemMisc:8").get(), new CTItemStack("actuallyadditions:blockCrystal:5").get()], [new CTItemStack("minecraft:lava_bucket").get(), new CTItemStack("minecraft:lava_bucket").get(), new CTItemStack("minecraft:lava_bucket").get()]]);